DEFRA/grants-ui

- src/config/nunjucks/filters/format-currency.js
- src/config/nunjucks/filters/format-currency.test.js
- src/server/common/forms/definitions/adding-value.json
- src/server/index.js
@ScenarioFactory This solution satisfies the logic in the ticket, and fixes the issue of the 695000 in project-cost not having a comma separator.
However, an important point is that because we are conditionally rendering content rather than having different pages, both of these have the same URL. Is this acceptable?
> add potential grant funding pages

- src/client/stylesheets/components/_index.scss
- src/config/config.js
- src/config/nunjucks/context/context.test.js
- src/server/common/components/account-bar/_account-bar.scss
- src/server/common/components/account-bar/macro.njk
- src/server/common/components/account-bar/template.njk
- src/server/common/helpers/errors.test.js
- src/server/common/helpers/logging/logger-options.js
- src/server/common/templates/layouts/page.njk
- src/server/home/index.njk
To bring the UI closer inline with what is shown in the prototype
I created a new component called `Defra Account Bar` which displays the current users name, business name and SBI. Its a similar pattern used on Single Front Door but with improved markup (I.e not using `h3` for the larger/bolder text). The component will only display is username and business name are passed to it. 
- Display new Defra Account Bar in the service using fake username/business name which can later be updated from Defra ID
- Updated the serviceName from `grants-ui` to `Manage land-based actions` 
- Added the service navigation component which is the new pattern that GOV.UK will be moving to instead of displaying the name in the Header
- Add simple phase banner for the moment
> Add new Defra Accounts Bar component and update page headings

- src/server/common/templates/layouts/page.njk
This will hide the account bar until we have defra id setup
> Removed user/business name from account bar

- package-lock.json
- package.json
- src/client/stylesheets/application.scss
- src/config/nunjucks/nunjucks.js
- src/server/common/forms/definitions/adding-value.json
- src/server/common/helpers/serve-static-files.js
- src/server/common/templates/layouts/dxt-form.njk
- src/server/common/templates/layouts/form.njk
- src/server/common/templates/layouts/page.njk
- src/server/index.js
- src/server/land-grants/actions/land-actions.html
- src/server/land-grants/parcel/land-parcel.html
- src/server/land-grants/submission/submission.html
- src/server/views/confirmation-page.html
- src/server/views/declaration-page.html
- src/server/views/score-results.html
- webpack.config.js
Creates a new `layouts/form.njk`, based off our base `layouts/page.njk` template. This `form.njk` template adds any required alterations for a form to be presented.
This PR is not quite ready to be merged, I'm having one issue with the initialisation of a YesNo component on a form - just trying to work that out. It's completely unrelated to this change, not quite sure what's going on!
There's a dependency on the next version of the plugin, which hasn't been published yet. See: https://github.com/DEFRA/forms-engine-plugin/pull/60
Old:
New:
> Use custom layout for DXT form pages

- src/server/common/forms/definitions/find-funding-for-land-or-farms.json
Updated the page heading to use sentence case for consistency with style guidelines.
> Change "Funding Details" and "Total Application Value" to sentence case 

- src/server/common/templates/layouts/dxt-form.njk
DXT form pages were not surfacing the form name but instead displaying the `serviceName`. This fixes the initial issue #66  introduced but we still need to flesh out a bit more on what `grants-ui` servicename will be
> Update DXT custom form layout to use form name

- src/server/common/services/grant-application.service.js
- src/server/common/services/grant-application.service.test.js
At the moment, our GAS service methods only support calls to POST actions with a payload. This PR enhances those methods to also support GET, passing query string parameters if present.
> Extend GAS service methods to support GET and query parameters

- src/config/config.js
- src/server/__mocks__/consolidated-view/106238988.json
- src/server/__mocks__/consolidated-view/106284736.json
- src/server/__mocks__/consolidated-view/121428499.json
- src/server/common/forms/definitions/find-funding-for-land-or-farms.yaml
- src/server/common/services/consolidated-view.service.js
- src/server/common/services/consolidated-view.service.test.js
At the moment, our application queries a DAL url on a real environment which is defined on the CV_API_ENDPOINT environment variable.
This is to add the ability to bypass calling the consolidated DAL API endpoint and serve static data instead.
CV_API_MOCK_ENABLED=true
> Mocking DAL based on env variable

- src/server/common/forms/definitions/find-funding-for-land-or-farms.yaml
We've lost our 'Continue' buttons in some of the steps of the form when we don't set the 'next' property on the form definition, possibly due to a change on DXT engine side.
This PR switches our forms engine to V2, which modifies this specific behaviour (among other changes that have no impact on our flow) and this will automatically display 'Continue' as long as the controller on the form definition is not of Type = Terminal.
> Add missing 'Continue' buttons on FRPS forms

- src/server/land-grants/actions/land-actions-check-page.controller.js
- src/server/land-grants/actions/land-actions-check-page.controller.test.js
- src/server/land-grants/actions/land-actions-check.html
This PR presents a YES/NO question on the actions check page to offer the ability to add more land actions to a different land parcel:
> RPS-676 - Flow changes: ability to add more actions to land

- src/server/land-grants/controllers/land-actions-page.controller.js
- src/server/land-grants/controllers/land-actions-page.controller.test.js
- src/server/land-grants/views/choose-which-actions-to-do.html
Display land parcel information on actions page:
Information data is still not available, as it requires an API change.
> RPS-696 - Land Grants actions page: display land parcel information card

- src/server/common/forms/definitions/find-funding-for-land-or-farms.yaml
- src/server/land-grants/controllers/land-actions-page.controller.js
- src/server/land-grants/controllers/land-actions-page.controller.test.js
- src/server/land-grants/controllers/land-parcel-page.controller.js
- src/server/land-grants/controllers/land-parcel-page.controller.test.js
- src/server/land-grants/mappers/state-to-gas-answers-mapper.js
- src/server/land-grants/mappers/state-to-gas-answers-mapper.test.js
- src/server/land-grants/views/choose-which-actions-to-do.html
- src/server/land-grants/views/select-land-parcel.html
This PR enables sending multiple parcel data to GAS on land grants form submission.
There are some variables in our form definition that we don't need anymore, as we're replacing them with more complex objects to better support multiple parcels and actions being submitted. This PR gets rid of the old variables from the form definition and code.
> Future RPS - Send multiple parcels to GAS and remove unneeded DXT variables from form definition

- src/server/land-grants/controllers/land-actions-page.controller.js
- src/server/land-grants/controllers/land-actions-page.controller.test.js
- src/server/land-grants/services/land-grants.service.js
- src/server/land-grants/services/land-grants.service.test.js
This PR removes parcel information we don't need to display on parcel actions page, so we'll only display total size for the time being:
> Remove unused parcel info on parcel actions page

- src/server/land-grants/controllers/__mocks__/unitRatesForActions.js
- src/server/land-grants/controllers/land-actions-check-page.controller.js
- src/server/land-grants/controllers/land-actions-page.controller.js
I decided to inline the mock values because the mock file was not available in production
> Fix mock data for payment not loading

- src/config/agreements.js
- src/server/agreements/controller.js
- src/server/agreements/controller.test.js
* The `x-encrypted-auth` header should include:
* **sbi** - in the future will be provided by `defra-id`
* **source** - which will always be 'defra' from `grants-ui`
* Renamed `AgreementsConfig` environment variables - Removed the redundant agreements prefix
**Resolves:** FRPSSFI-239 FRPSSFI-185
> FRPSSFI-239 Add 'x-encrypted-auth' to agreements request headers

- package-lock.json
- src/server/common/helpers/state/get-cache-key-helper.js
- src/server/common/helpers/state/persist-state-helper.js
- src/server/common/helpers/state/persist-state-helper.test.js
- src/server/index.js
Adds session persistence to DXT to complement session rehydration. This ensures session state is saved not just to cache but also asynchronously to a backend store, enabling Save & Return functionality across devices and sessions.
- persistStateToApi that is called within DXT's handleSaveAndReturn to persists session state to backend
- Replaces reliance on cacheService.setState for Save & Return
- Improves session durability and supports multi-device use
This is the first iteration for security scan (note there will be still some work to be added for resilient persister similar to what was done for session purging and for error handling/messaging to the UX when session persisting fails).
> State persister for save and return

- src/server/land-grants/views/select-land-parcel.html
Update the select parcels page to match prototype:
https://eaflood.atlassian.net/browse/SFIR-203
@aliuk2012 - Here is the ui, the gap between the header and the first line of text, is slightly different to the prototype, but I think the prototype is wrong.
In order to add this new line of text, I have added a header, and changed the fieldlist text to the new text, i guess there are many ways to do this, let me know if you prefer another way.
> Update select parcels page to match prototype

- src/server/common/forms/definitions/find-funding-for-land-or-farms.yaml
- src/server/land-grants/mappers/state-to-gas-answers-mapper.js
- src/server/land-grants/mappers/state-to-gas-answers-mapper.test.js
This pr remove the agreement name page, https://eaflood.atlassian.net/browse/SFIR-263
- Also defaults the agreement name to NO_LONGER_REQUIRED
- Removing the page, has also correctly removed the page from the summary
- Updated the tests
> Remove the agreement name page

- src/server/common/forms/definitions/find-funding-for-land-or-farms.yaml
- src/server/land-grants/mappers/state-to-gas-answers-mapper.js
- src/server/land-grants/mappers/state-to-gas-answers-mapper.test.js
- src/server/land-grants/views/confirm-your-land-details-are-up-to-date.html
This pr adds a new confirm land details page, and also removes the digital maps show the correct page
https://eaflood.atlassian.net/browse/SFIR-163
- remove `digital maps show the correct` page
- remove the condition for this page
- remove the `You must correct your land details` page
- set `hasCheckedLandIsUpToDate` = true on sending application to gas
> Sfir 163 confirm land details

- src/server/land-grants/controllers/select-actions-for-land-parcel-page.controller.js
- src/server/land-grants/controllers/select-actions-for-land-parcel-page.controller.test.js
- src/server/land-grants/views/select-actions-for-land-parcel.html
Previously, farmers were able to select multiple actions for a specific land parcel at a time. The new behaviour is that they will only be able to select one land action for a specific land parcel
> Update "Select actions for land parcel" page

- src/server/land-grants/views/select-actions-for-land-parcel.html
Without this there ends up being an issue with the markup as the two groups would have an id of `landActions`
> Set id for livestock grazing group of land actions

- src/server/land-grants/controllers/select-actions-for-land-parcel-page.controller.js
- src/server/land-grants/controllers/select-actions-for-land-parcel-page.controller.test.js
- src/server/land-grants/views/select-actions-for-land-parcel.html
Currently if the user does not select a land action and tried to move to the next page, they would get a 500 error page.
> Fix land actions validations

- src/server/land-grants/views/select-actions-for-land-parcel.html
We removing this error message as we have two "groupings" of radio buttons which we would want to show as being invalid. The GOV.UK Design System doesn't support what we want to do on this page. We also know the design of this page will change to help support farmers select multiple land actions/land parcels.
> Remove inline error message

- src/server/common/components/account-bar/template.njk
- src/server/common/templates/layouts/dxt-form.njk
- src/server/common/templates/layouts/page.njk
On all pages throughout the service will now include an "Account Bar" directly below the phase banner with the authenticated users details.
> Pass authenticated users details to AccountBar component

- src/config/config.js
- src/config/nunjucks/nunjucks.js
- src/server/common/templates/layouts/page.njk
- src/server/views/layout.page.njk
Introduced configuration for Google Analytics tracking ID in `config.js`. Updated Nunjucks templates and configuration to include the tracking ID dynamically and embed the required script for Google Tag Manager when the ID is present.
> Add Google Analytics tracking support

- README.md
- compose.yml
- mockserver/expectations.json
Extend compose.yml to work as follows 'out of the box':
- Enable Defra ID in Basic mode, will respond to any CRN and password with a choice of 3 SBIs.
- Enable authentication between grants-ui and grants-ui-backend.
- Use MockServer as a stub for GAS. Requests sent to GAS can be viewed at http://localhost:1080/mockserver/dashboard.
> Extend compose file with GAS stub and enable Defra ID

- src/server/land-grants/controllers/land-actions-check-page.controller.js
- src/server/land-grants/controllers/land-actions-check-page.controller.test.js
- src/server/land-grants/views/land-actions-check.html
As per GOVUK guidelines, numeric values should be aligned to the right. Also, the yearly payments columns are on the same position between tables. 
Before:
After:
> Actions review page style fixes

- eslint.config.js
- src/plugins/auth.test.js
- src/server/common/helpers/redis-client.test.js
- src/server/common/helpers/state/backend-auth-helper.test.js
- src/server/land-grants/controllers/auth/land-grants-question-with-auth-check.controller.js
- src/server/land-grants/controllers/auth/land-grants-question-with-auth-check.controller.test.js
- src/server/land-grants/controllers/land-parcel-page.controller.js
- src/server/land-grants/controllers/land-parcel-page.controller.test.js
- src/server/land-grants/controllers/remove-action-page.controller.js
- src/server/land-grants/controllers/remove-action-page.controller.test.js
- src/server/land-grants/controllers/select-actions-for-land-parcel-page.controller.js
- src/server/land-grants/controllers/select-actions-for-land-parcel-page.controller.test.js
- src/server/land-grants/views/unauthorised.html
Use a list of Land Parcels from DAL to determine whether the select land parcel is own by the users SBI before allowing them to Add/Edit/Delete/View
When a farmer tries to access a land parcel that their SBI does not own then they will see the following page
> Restrict farmers to only Add/Edit/Delete/View land actions for land parcels they own

- src/server/common/forms/definitions/find-funding-for-land-or-farms.yaml
The user should be going straight to "confirm their detail" page after they have logged in and not have to manually click "Start" button.
> Remove start page holding page from land grants user journey

- src/server/land-grants/controllers/land-parcel-page.controller.js
- src/server/land-grants/controllers/land-parcel-page.controller.test.js
- src/server/land-grants/controllers/remove-action-page.controller.js
- src/server/land-grants/controllers/remove-action-page.controller.test.js
- src/server/land-grants/controllers/select-actions-for-land-parcel-page.controller.js
- src/server/land-grants/controllers/select-actions-for-land-parcel-page.controller.test.js
I accidentally called performAuthCheck with three arguments rather than two. I have also added some specs to catch this sort of error out again.
> Add `performAuthCheck` verification in tests & call it correctly

- src/server/common/components/account-bar/template.njk
- Use GOV.UK Lint styling rather than default browser font colour
- Change sign-out link font weight to regular so it's not so dominant  on the page
> Fix styling of signout link

- acceptance/gae-compose.yml
As per the grants-ui-backend and ffc-grants-scoring images, ensure we always pull the latest test suite when working with acceptance tests.
> Use pull_policy:always for acceptance tests image

- src/server/land-grants/controllers/submission-page.controller.js
- src/server/land-grants/controllers/submission-page.controller.test.js
This PR adds submission logic on the land grants submission controller to ensure we're notifying and updating grants-ui-backend application status.
> Update grants-ui-backend application status on land grants submission
